config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'welcome#home'

  resources :personalities, only: [:new, :create, :update, :edit]

  resources :users, only: [:show] do
    resources :matches, only: [:index]
  end

  resources :users, only: [:index]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :personality_type
  belongs_to :partner_type, class_name: 'PersonalityType'
end

app/models/personality.rb
class Personality < ApplicationRecord
  belongs_to :user
  # has_many :matches, as: :user
  # has_many :matches, as: :compatibility
  validates_presence_of :intro_extroversion, :user_id, :sensing_intuition, :thinking_feeling, :judging_perceiving

  def self.questions
    ["Being around people energizes me.",
     "I need time alone to recharge my batteries.",
     "I pay attention to details and think in concrete terms.",
     "I prefer to look at the 'big picture' and think in abstract terms.",
     "I make decisions based on logic.",
     "I make decisions based on my values.",
     "I make plans in advance and prefer organization and structure.",
     "I 'go with the flow' and prefer to keep plans casual."]
  end

  def type
    self.intro_extroversion + self.sensing_intuition + self.thinking_feeling + self.judging_perceiving
  end

end

app/models/personality_type.rb
class PersonalityType < ApplicationRecord
  has_many :users
  has_many :matches
  has_many :matches, as: :partner_type

  def url
    "https://www.16personalities.com/#{self.name}-personality"
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :personality
  belongs_to :personality_type, optional: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/personalities_controller.rb
class PersonalitiesController < ApplicationController
  def new
    @personality = Personality.new
    @personality_questions = Personality.questions
  end

  def create
    @personality = Personality.new(personality_params)
    if @personality.save
      type = PersonalityType.find_by(name: @personality.type)
      type.users << current_user
      redirect_to user_path(current_user)
    else
      @personality = Personality.new
      @personality_questions = Personality.questions
      render 'new'
    end
  end

  def edit
    @personality = Personality.find(params[:id])
    @personality_questions = Personality.questions
  end

  def update
    @personality = Personality.find(params[:id])
    @personality.update(personality_params)
    redirect_to user_path(current_user)
  end

  private

  def personality_params
    params.require(:personality).permit(:user_id, :intro_extroversion, :sensing_intuition, :thinking_feeling, :judging_perceiving)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :current_password)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @matches = Match.where(personality_type_id: @user.personality_type)
  end

  def index
    @users = User.all
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!

  def home
    if current_user && current_user.personality.nil?
      redirect_to new_personality_path
    elsif current_user
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-custom">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><span class="orchid">&hearts;</span> PersonalityMatch</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <!-- <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul> -->
      <!-- <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form> -->
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li><%= link_to "#{current_user.username}", user_path(current_user) %></li>
          <li><%= link_to "Browse Users", users_path %></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: 'delete' %></li>
        <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
        <% end %>

        <!-- <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li> -->
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PersonalityMatch</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'layouts/nav' %>

    <%= yield %>

  </body>
</html>

app/views/personalities/_form.html.erb
<%= form_for @personality do |f| %>

  <%= f.hidden_field :user_id, value: current_user.id %>

  1. <%= f.radio_button :intro_extroversion, "E" %>
  <%= label :intro_extroversion, "#{@personality_questions[0]}" %>


  <br> OR <br>

  <%= f.radio_button :intro_extroversion, "I" %>
  <%= label :intro_extroversion, "#{@personality_questions[1]}" %>
  <br>
  <br>

  2. <%= f.radio_button :sensing_intuition, "S" %>
  <%= label :sensing_intuition, "#{@personality_questions[2]}" %>


  <br> OR <br>

  <%= f.radio_button :sensing_intuition, "N" %>
  <%= label :sensing_intuition, "#{@personality_questions[3]}" %>
  <br>
  <br>

  3. <%= f.radio_button :thinking_feeling, "T" %>
  <%= label :thinking_feeling, "#{@personality_questions[4]}" %>

  <br> OR <br>

  <%= f.radio_button :thinking_feeling, "F" %>
  <%= label :thinking_feeling, "#{@personality_questions[5]}" %>
  <br>
  <br>

  4. <%= f.radio_button :judging_perceiving, "J" %>
  <%= label :judging_perceiving, "#{@personality_questions[6]}" %>

  <br> OR <br>

  <%= f.radio_button :judging_perceiving, "P" %>
  <%= label :judging_perceiving, "#{@personality_questions[7]}" %>
  <br>
  <%= f.submit "Submit", :class => "btn btn-primary"%>

<% end %>

app/views/personalities/edit.html.erb
<div class="container-fluid text">
  <h1>Retake the Test</h1>
  <%= render 'form' %>
</div>

app/views/personalities/new.html.erb
<div class="container-fluid text">
  <h1>Personality Test</h1>
  <%= render 'form' %>
</div>

app/views/users/index.html.erb
<div class="container-fluid text">
  <h1>Browse Users</h1>

  <% @users.each do |user| %>
    <%= link_to user.username, user_path(user) %>, <%= link_to user.personality_type.name, user.personality_type.url, target: "_blank" %><br>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container-fluid text">
  <% if @user == current_user %>
    <h1>Hi, <%= @user.username %></h1>


    <h3>Your Personality Type: <%= link_to @user.personality.type, @user.personality_type.url, :target => "_blank" %></h3>
    <p><%= link_to "Retake", edit_personality_path %></p>


    <h3>Your Matches</h3>
    <% if @matches %>
      <% @matches.each do |match| %>
        <% match.partner_type.users.each do |user| %>
          <%= link_to user.username, user_path(user) %>, <%= link_to user.personality_type.name, user.personality_type.url, target: "_blank" %><br>
        <% end %>
      <% end %>
    <% end %>
  <% else %>
    <h1><%= @user.username %></h1>
    <h3><%= link_to @user.personality.type, @user.personality_type.url, target: "_blank" %></h3>
  <% end %>
</div>

app/views/welcome/home.html.erb
<body class="center text">
  <div class="container-fluid">
    <h1 id="welcome-heading"><span class="orchid">&hearts;</span> PersonalityMatch</h1>
    <h3><%= link_to "Sign In", new_user_session_path %></h3>
    <h3><%= link_to "Sign Up", new_user_registration_path %></h3>
  </div>
</body>